# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JLqfOEkxZvqRtNnsARzpP1n7rMaSlObq
"""

num = 6
for i in range(0, num):
    for j in range(0, num-i-1):
        print(end=" ")
    for j in range(0, i+1):
        print("*", end=" ")
    print()

rows = 5
for i in range(0,5,1):
  print("*"*i)
for j in range(5,0,-1):
  print("*"*j)

rows = 6
for i in range(0,rows,1):
  print("*"*i)

rows = 5
for i in range(rows,0,-1):
  print("*"*i)



nums = [10,20,3,4,36,78,90,100]
def test(nums):
  sum = 0
  for i in nums:
    sum += i
  return sum
print(test(nums))

def test(nums):
    product = 1
    for i in nums:
        product *= i
    return product
print(test(nums))

# max
def test(nums):
  return max(nums)
print(test(nums))

# maximum
nums = [1, 2, -8, 0]
def test(nums):
  return max(nums)
print(test(nums))

# minimum
def test(nums):
  return min(nums)
print(test(nums))

def match_words(words):
  ctr = 0

  for word in words:
    if len(word) > 1 and word[0] == word[-1]:
      ctr += 1
  return ctr

print(match_words(['abc', 'xyz', 'aba', '1221']))

a = ['abc', 'xyz', 'aba', '1221']
def test(a):
  b = 0
  for i in a:
    if len(i) > 1 and i[0] == i[-1]:
      b = b + 1
  return b
print(test(a))

a = [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
def last(n): return n[-1]

def a(tuples):
  return sorted(tuples, key=last)

a = [10,20,30,20,10,50,60,40,80,50,40]

dup_items = set()
uniq_items = []
for x in a:
    if x not in dup_items:
        uniq_items.append(x)
        dup_items.add(x)

print(dup_items)

# remove duplicate
a = [10,20,30,20,10,50,60,40,80,50,40]
print(len(a))
duplicate = set()
list = []
for i in a:
  if i not in duplicate:
    list.append(i)
    duplicate.add(i)
print(sorted(duplicate))
print(sorted(list))

# check whether list is empty or not
list = [10,20]

if len(list) > 1:
  print("list is not empty")
else:
  print("list is empty")

# copy list or cloning of list
list1 = [10,56,89,74]
import copy
list2 = copy.deepcopy(list1)
print(list2)

# program to find the list of words that are longer than n from a given list of words.
list = ["pritam", "python", "data", "mobile", "laptop"]
list1 = []
for i in list:
  if len(i) > 3:
    list1.append(i)
print(list1)

# 11. common in list
a = [10,20,6,0,3,78]
b = [156,45,86,77,2]

def test(a,b):
  result = False
  for i in a:
    for j in b:
      if i == j:
        result = True
        return result
print(test(a,b))

# 12. remove the 0th, 4th and 5th element
color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
b = [x for (i,x) in enumerate(color) if i not in (0,4,5)]
print(b)

array = [[ ['*' for col in range(6)] for col in range(4)] for row in range(3)]
print(array)

# new list after removing even nums
nums = [1,2,3,4,5,6,7,8,9,10]
odd_nums = []
for i in nums:
  if i%2 != 0:
    odd_nums.append(i)
print(odd_nums)

print(max(odd_nums))

# program to shuffle and print a specified list.
from random import shuffle
color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
shuffle(color)
print(color)

# write program first and last 5 nos of (1,20 range)
def square():
  list = []
  for i in range(1,21):
    list.append(i**2)
    list[:5]
    list[-5:]
  print(list)
  print(list[:5])
  print(list[-5:])
square()

# generate and print a list except for the first and last 5 elements, where the values are square of numbers between 1 and 30 (both included
def square():
  list = []
  for i in range(1,31):
    list.append(i**2)
    list[5:25]
  print(list[5:25])
square()

# to generate all permutations of a list in Python.
import itertools
print(tuple(itertools.permutations([1,2,3])))

# difference between two list
a = [10,20,30,48,96]
b = [5,65,58,20,35]
diff = tuple(set(a)-set(b))
print(diff)
print("-------------")
diff1= tuple(set(b)-set(a))
print(diff1)

# access index number
list = [10,20,6,3,50,5,3,58,9,32,8]
for index,value in enumerate(list):
  print(index,value)

#  convert list of charachters into string
s = ['a', 'b', 'c', 'd']
string = "".join(s)
print(string)
print(type(string))

# Python program to append a list to the second list
a = [1,2,3,4,5,6,7,8,9,10]
list = []
for i in a:
  list.append(i)
print(list)

# program to select an item randomly from a list
list = ["orange","banana","cherry","peru"]
import random
choice = random.choice(list)
print(choice)

a = random.shuffle(list)
print(a)