"""Rock-Paper-Scissor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVvZ0tcbVEdY_ZYTzZ5cHHpVqd9tNpUX
"""

# Rock Paper Scissor
import random

print("Welcome!! Rock-Paper-Scissor")
"""Game rules--

Rock smashes scissors.
Paper covers rock.
Scissors cut paper.

if rock and scissor ==> rock wins
if paper and rock ==> paper wins
if scissor and paper ==> scissor wins"""

print("""please enter your choice:
1.Rock
2.Paper
3.Scissor""")

while True:

  user = int(input("please enter your choice:"))

  if user == 1:
    user_choice = "Rock"
    print("your choice is:", user_choice)
  elif user == 2:
    user_choice = "Paper"
    print("your choice is:", user_choice)
  else:
    user_choice = "Scissor"
    print("your choice is:", user_choice)

  # if choice is wrong
  while user>3 and user<1:
    user = int(input("please enter valid choice:"))

  computer = random.randint(1,3)
  #print(computer)
  
  # assign number to variables
  if computer == 1:
    computer_choice = "Rock"
    print("computer choice is:", computer_choice)
  elif computer == 2:
    computer_choice = "Paper"
    print("computer choice is:", computer_choice)
  else:
    computer_choice = "Scissor"
    print("computer choice is:", computer_choice)

  if (user_choice== "Paper" and computer_choice=="Rock") or (user_choice=="Rock" and computer_choice=="Paper"):
    print("Paper wins!!")
    result = "Paper"
  elif (user_choice== "Scissor" and computer_choice=="Rock") or (user_choice=="Rock" and computer_choice=="Scissor"):
    print("Rock wins!!")
    result = "Rock"
  elif (user_choice==computer_choice):
    print("Its tie")
    result = "Tie"

  else:
    print("Scissor wins!!")
    result = "Scissor"

  # scores
  if result == "Tie":
    tie = tie + 1
  elif result == user_choice:
    user_score = user_score + 1
    print("user wins!!")
  else:
    computer_score = computer_score + 1
    print("computer wins!!!")
    
  print("tie score:", tie)
  print("user score:",user_score)
  print("computer score:",computer_score)